<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="LibSodium.Net.Tests.Core.csproj" />
	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<RuntimeIdentifier>android-x64</RuntimeIdentifier>
		<DefineConstants>ANDROID</DefineConstants>
		<NoWarn>$(NoWarn);IL2037</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FSharp.Core" Version="10.1.400" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" ExcludeAssets="all" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
	</ItemGroup>
</Project>
