<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="LibSodium.Net.Tests.Core.csproj" />
	<PropertyGroup>
		<TargetFramework>net10.0-ios</TargetFramework>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<UseInterpreter>false</UseInterpreter>
		<PublishTrimmed>true</PublishTrimmed>
		<PublishAot>true</PublishAot>
		<DefineConstants>IOS</DefineConstants>
		<ApplicationId>net.libsodium.tests</ApplicationId>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
</Project>
